// The arpeggiator, as a pure function over notes.
//
// WHY A TRANSFORM AND NOT A LIVE DEVICE. An arpeggiator can be either: a
// note effect that turns held chords into a stream on the way to the
// instrument, or a generator that rewrites the notes in the clip. This app
// does the second, and the reasons are architectural rather than aesthetic:
//
//   - It is ONE COMMAND and one undo entry. The result is in the document,
//     so it plays, exports, saves and reopens identically, with no second
//     scheduler to keep in step with SS8's tick<->seconds conversion.
//   - You can SEE it, and then edit it. Half of what people do with an arp
//     is nudge two of its notes afterwards, which a black box forbids.
//   - The original is one Undo away, which is the honest version of the
//     "bypass" button a live device would need.
//
// The model matches what a live arp does, so the result is the same music:
// walk the selection's span in steps, and at each step play ONE of the
// pitches sounding at that moment, taken in the chosen order. Held notes and
// overlapping chords therefore work without a separate notion of "chord" —
// what is sounding at a step IS the chord.

import type { ArpMode, ArpOptions, NoteInit, Ticks } from "../types";
import { ARP_MODES, arpOrder } from "../music/arpeggio";

export type { ArpMode, ArpOptions };
// Re-exported, not redefined: the live note effect (`core.arpeggiator`) walks
// its chords in the same order this transform does, and one copy of that rule
// is the only way that stays true. See src/music/arpeggio.ts.
export { ARP_MODES, arpOrder };

export const DEFAULT_ARP_OPTIONS: ArpOptions = {
  step: 240, // a 1/16 note at PPQ 960
  mode: "up",
  octaves: 1,
  gate: 90,
};

/** The minimum a source note has to contribute to be worth a step. */
const MIN_SOURCE_TICKS = 1;

/** What the transform reads off a note — narrower than `Note`, so a test can
 *  hand it plain objects and the command can hand it document notes. */
export interface ArpSource {
  readonly start: Ticks;
  readonly dur: Ticks;
  readonly pitch: number;
  readonly vel: number;
}

/** Pitches sounding at `tick`, low to high, deduplicated. */
function soundingAt(notes: readonly ArpSource[], tick: Ticks): ArpSource[] {
  const out: ArpSource[] = [];
  for (const note of notes) {
    if (note.start <= tick && tick < note.start + Math.max(MIN_SOURCE_TICKS, note.dur)) {
      out.push(note);
    }
  }
  return out;
}

/**
 * Rewrites `notes` as an arpeggio.
 *
 * Returns the REPLACEMENT set, without ids — the caller mints them (SS13:
 * "ids are generated by the factory functions, never inside `run`"). An empty
 * input, a zero-length span or a non-positive step all return `[]`, which the
 * command treats as "nothing to do" rather than as an error.
 */
export function arpeggiate(
  notes: readonly ArpSource[],
  options: ArpOptions,
): Array<Omit<NoteInit, "id">> {
  const step = Math.max(1, Math.round(options.step));
  if (notes.length === 0) return [];

  let spanStart = Number.POSITIVE_INFINITY;
  let spanEnd = Number.NEGATIVE_INFINITY;
  for (const note of notes) {
    if (note.start < spanStart) spanStart = note.start;
    const end = note.start + Math.max(MIN_SOURCE_TICKS, note.dur);
    if (end > spanEnd) spanEnd = end;
  }
  if (!(spanEnd > spanStart)) return [];

  const octaves = Math.max(1, Math.min(4, Math.round(options.octaves)));
  const gate = Math.max(1, options.gate) / 100;
  const random = options.random ?? Math.random;

  const out: Array<Omit<NoteInit, "id">> = [];
  // The order index runs across the WHOLE span, not per chord: that is what
  // makes an arp keep its place when the chord underneath it changes, which
  // is the entire musical point of playing one over a progression.
  let orderIndex = 0;

  for (let at = spanStart; at < spanEnd; at += step) {
    const sounding = soundingAt(notes, at);
    if (sounding.length === 0) {
      // A gap in the selection stays a gap; the pattern does not slide over
      // it. Advancing the index anyway would make the rest of the phrase
      // depend on how long the rest was.
      continue;
    }
    const ordered =
      options.mode === "asPlayed"
        ? [...sounding].sort((a, b) => a.start - b.start || a.pitch - b.pitch)
        : [...sounding].sort((a, b) => a.pitch - b.pitch);

    // Octave expansion: the same voices again, an octave up each time.
    const voices: ArpSource[] = [];
    for (let octave = 0; octave < octaves; octave++) {
      for (const note of ordered) voices.push({ ...note, pitch: note.pitch + 12 * octave });
    }

    const order = arpOrder(voices.length, options.mode);
    if (order.length === 0) continue;
    const pick =
      options.mode === "random"
        ? Math.min(voices.length - 1, Math.floor(random() * voices.length))
        : (order[orderIndex % order.length] ?? 0);
    const voice = voices[pick];
    orderIndex++;
    if (voice === undefined) continue;

    // Never past the end of the span: an arp that spills over its own
    // selection would grow the clip every time it was run again.
    const dur = Math.max(1, Math.min(Math.round(step * gate), spanEnd - at));
    out.push({
      start: at,
      dur,
      pitch: Math.max(0, Math.min(127, Math.round(voice.pitch))),
      vel: voice.vel,
    });
  }
  return out;
}
