// SS13 — id generation for the document layer.
//
// "Ids are generated by the factory functions, never inside `run`"
// (types/commands.ts `Command`): redo re-applies recorded patches instead of
// re-running the command, so an id minted inside `run` would differ between
// the original dispatch and any later replay. Every `*Init` therefore accepts
// a pinned id, and every factory that creates something mints its ids EAGERLY
// from an `IdFactory`.
//
// Ids are embedded verbatim in `ParamId` paths (SS4:
// `chan:<ChannelId>/dev:<DeviceInstanceId>/<localId>`), so they must never
// contain the path separator `/` — the generators below emit
// `[a-z0-9-]` only.

import type {
  ChannelId,
  ClipId,
  DeviceInstanceId,
  IdFactory,
  LaneId,
  NoteId,
  ProjectId,
  RackChainId,
  RackId,
  RackMacroId,
} from "../types";

/** Kind prefixes. Short on purpose: these strings end up inside every
 *  `ParamId` and inside every saved project file. */
const PREFIX = {
  project: "prj",
  channel: "chan",
  device: "dev",
  clip: "clip",
  note: "note",
  lane: "lane",
  rack: "rack",
  chain: "rchain",
  macro: "macro",
} as const;

export interface IdFactoryOptions {
  /** Injectable randomness so a test can pin the output. Default
   *  `Math.random`. */
  random?: (() => number) | undefined;
  /** Extra namespace segment, e.g. a session tag. Must be `[a-z0-9-]`. */
  namespace?: string | undefined;
}

const TOKEN_RADIX = 36;

function token(random: () => number, seq: number): string {
  const rand = Math.floor(random() * 0xffffffff)
    .toString(TOKEN_RADIX)
    .padStart(6, "0")
    .slice(-6);
  return `${seq.toString(TOKEN_RADIX)}${rand}`;
}

/**
 * The shipped factory: a per-instance counter (uniqueness within a session)
 * plus a random suffix (uniqueness across sessions, so ids from two machines
 * or two tabs never collide inside one project file).
 */
export function createIdFactory(options: IdFactoryOptions = {}): IdFactory {
  const random = options.random ?? Math.random;
  const ns = options.namespace === undefined ? "" : `${options.namespace}-`;
  let seq = 0;
  const next = (prefix: string): string => {
    seq += 1;
    return `${prefix}-${ns}${token(random, seq)}`;
  };
  return {
    project: (): ProjectId => next(PREFIX.project),
    channel: (): ChannelId => next(PREFIX.channel),
    device: (): DeviceInstanceId => next(PREFIX.device),
    clip: (): ClipId => next(PREFIX.clip),
    note: (): NoteId => next(PREFIX.note),
    lane: (): LaneId => next(PREFIX.lane),
    rack: (): RackId => next(PREFIX.rack),
    chain: (): RackChainId => next(PREFIX.chain),
    macro: (): RackMacroId => next(PREFIX.macro),
  };
}

/**
 * Fully deterministic factory (`chan-1`, `chan-2`, `clip-1`, ...). For unit
 * tests and for fixtures whose ids appear in assertions; never for a real
 * session, where two documents would mint colliding ids.
 */
export function createSequentialIdFactory(prefixTag = ""): IdFactory {
  const counters = new Map<string, number>();
  const ns = prefixTag === "" ? "" : `${prefixTag}-`;
  const next = (prefix: string): string => {
    const n = (counters.get(prefix) ?? 0) + 1;
    counters.set(prefix, n);
    return `${prefix}-${ns}${n}`;
  };
  return {
    project: (): ProjectId => next(PREFIX.project),
    channel: (): ChannelId => next(PREFIX.channel),
    device: (): DeviceInstanceId => next(PREFIX.device),
    clip: (): ClipId => next(PREFIX.clip),
    note: (): NoteId => next(PREFIX.note),
    lane: (): LaneId => next(PREFIX.lane),
    rack: (): RackId => next(PREFIX.rack),
    chain: (): RackChainId => next(PREFIX.chain),
    macro: (): RackMacroId => next(PREFIX.macro),
  };
}

/** Process-wide default used by `projectCommands` and `createEmptyProject`
 *  when no factory is supplied. */
export const defaultIdFactory: IdFactory = createIdFactory();
